server:
  port: 8080
  tomcat:
    threads:
      max: 1000       # 最大工作线程数（默认200，太小了）
      min-spare: 100  # 最小空闲线程数
    max-connections: 2000 # 最大连接数
    accept-count: 1000    # 队列长度

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}

  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    lettuce:
      pool:
        max-active: 50 # 最大连接数
        max-idle: 10   # 最大空闲连接
        min-idle: 2
        max-wait: 2000ms # 连接等待时间

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl:  31536000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: itheima
    user-token-name: authentication
    user-ttl: 31536000000
  alioss:
      access-key-id: ${sky.alioss.access-key-id}
      access-key-secret: ${sky.alioss.access-key-secret}
      endpoint: ${sky.alioss.endpoint}
      bucket-name: ${sky.alioss.bucket-name}
  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}
  shop:
    address: ${sky.shop.address}
  baidu:
    ak: ${sky.baidu.ak}
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: seckill-group
deepseek:
  api-key: ${sky.deepseek.api-key}
  api-url: https://api.deepseek.com/chat/completions
  timeout:
    connect: 10
    write: 10
    read: 30


